🐛 Fix build for Android 27
Includes updates to gradle config for:
* declaring annotation processors
* using v27 of libs
* updating gradle tools version

These changes allow the app to build, and deploy to emulator.
However, it crashes right away on below error.

```
06-20 22:34:38.739 11354-11354/org.feedhenry.apps.arthenry E/com.feedhenry.sdk.FHHttpClient: UnknownHostException exception: Unable to resolve host "aerogear-t.sandbox.feedhenry.com": No address associated with hostname
    java.io.IOException: UnknownHostException exception: Unable to resolve host "aerogear-t.sandbox.feedhenry.com": No address associated with hostname
        at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:183)
        at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
06-20 22:34:38.740 11354-11354/org.feedhenry.apps.arthenry E/com.feedhenry.sdk.FH: FH init failed with error = {}
    java.io.IOException: UnknownHostException exception: Unable to resolve host "aerogear-t.sandbox.feedhenry.com": No address associated with hostname
        at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:183)
        at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
06-20 22:34:38.741 11354-11354/org.feedhenry.apps.arthenry E/SPLASH: {}
06-20 22:34:38.742 11354-11354/org.feedhenry.apps.arthenry E/AsyncHttpRH: User-space exception detected!
    java.lang.RuntimeException: Could not dispatch event: class org.feedhenry.apps.arthenry.events.InitFailed to handler [EventHandler public void org.feedhenry.apps.arthenry.SplashScreen.onInitError(org.feedhenry.apps.arthenry.events.InitFailed)]: {}
        at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
        at com.squareup.otto.Bus.dispatch(Bus.java:387)
        at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
        at com.squareup.otto.Bus.post(Bus.java:337)
        at org.feedhenry.apps.arthenry.fh.FHClient.postConnectFailureRunner(FHClient.java:257)
        at org.feedhenry.apps.arthenry.fh.FHClient.access$300(FHClient.java:41)
        at org.feedhenry.apps.arthenry.fh.FHClient$1.fail(FHClient.java:91)
        at com.feedhenry.sdk.FH$1.fail(FH.java:193)
        at com.feedhenry.sdk2.FHHttpClient$FHJsonHttpResponseHandler.onFailure(FHHttpClient.java:235)
        at com.loopj.android.http.JsonHttpResponseHandler.onFailure(JsonHttpResponseHandler.java:233)
        at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:359)
        at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.RuntimeException: {}
        at org.feedhenry.apps.arthenry.SplashScreen.onInitError(SplashScreen.java:96)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
        at com.squareup.otto.Bus.dispatch(Bus.java:385)
        at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368) 
        at com.squareup.otto.Bus.post(Bus.java:337) 
        at org.feedhenry.apps.arthenry.fh.FHClient.postConnectFailureRunner(FHClient.java:257) 
        at org.feedhenry.apps.arthenry.fh.FHClient.access$300(FHClient.java:41) 
        at org.feedhenry.apps.arthenry.fh.FHClient$1.fail(FHClient.java:91) 
        at com.feedhenry.sdk.FH$1.fail(FH.java:193) 
        at com.feedhenry.sdk2.FHHttpClient$FHJsonHttpResponseHandler.onFailure(FHHttpClient.java:235) 
        at com.loopj.android.http.JsonHttpResponseHandler.onFailure(JsonHttpResponseHandler.java:233) 
        at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:359) 
        at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
06-20 22:34:38.743 11354-11354/org.feedhenry.apps.arthenry E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.feedhenry.apps.arthenry, PID: 11354
    java.lang.RuntimeException: java.lang.RuntimeException: Could not dispatch event: class org.feedhenry.apps.arthenry.events.InitFailed to handler [EventHandler public void org.feedhenry.apps.arthenry.SplashScreen.onInitError(org.feedhenry.apps.arthenry.events.InitFailed)]: {}
        at com.loopj.android.http.AsyncHttpResponseHandler.onUserException(AsyncHttpResponseHandler.java:304)
        at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:395)
        at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.RuntimeException: Could not dispatch event: class org.feedhenry.apps.arthenry.events.InitFailed to handler [EventHandler public void org.feedhenry.apps.arthenry.SplashScreen.onInitError(org.feedhenry.apps.arthenry.events.InitFailed)]: {}
        at com.squareup.otto.Bus.throwRuntimeException(Bus.java:460)
        at com.squareup.otto.Bus.dispatch(Bus.java:387)
        at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368)
        at com.squareup.otto.Bus.post(Bus.java:337)
        at org.feedhenry.apps.arthenry.fh.FHClient.postConnectFailureRunner(FHClient.java:257)
        at org.feedhenry.apps.arthenry.fh.FHClient.access$300(FHClient.java:41)
        at org.feedhenry.apps.arthenry.fh.FHClient$1.fail(FHClient.java:91)
        at com.feedhenry.sdk.FH$1.fail(FH.java:193)
        at com.feedhenry.sdk2.FHHttpClient$FHJsonHttpResponseHandler.onFailure(FHHttpClient.java:235)
        at com.loopj.android.http.JsonHttpResponseHandler.onFailure(JsonHttpResponseHandler.java:233)
        at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:359)
        at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
     Caused by: java.lang.RuntimeException: {}
        at org.feedhenry.apps.arthenry.SplashScreen.onInitError(SplashScreen.java:96)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.squareup.otto.EventHandler.handleEvent(EventHandler.java:89)
        at com.squareup.otto.Bus.dispatch(Bus.java:385)
        at com.squareup.otto.Bus.dispatchQueuedEvents(Bus.java:368) 
        at com.squareup.otto.Bus.post(Bus.java:337) 
        at org.feedhenry.apps.arthenry.fh.FHClient.postConnectFailureRunner(FHClient.java:257) 
        at org.feedhenry.apps.arthenry.fh.FHClient.access$300(FHClient.java:41) 
        at org.feedhenry.apps.arthenry.fh.FHClient$1.fail(FHClient.java:91) 
        at com.feedhenry.sdk.FH$1.fail(FH.java:193) 
        at com.feedhenry.sdk2.FHHttpClient$FHJsonHttpResponseHandler.onFailure(FHHttpClient.java:235) 
        at com.loopj.android.http.JsonHttpResponseHandler.onFailure(JsonHttpResponseHandler.java:233) 
        at com.loopj.android.http.AsyncHttpResponseHandler.handleMessage(AsyncHttpResponseHandler.java:359) 
        at com.loopj.android.http.AsyncHttpResponseHandler$ResponderHandler.handleMessage(AsyncHttpResponseHandler.java:510) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

This is OK imo, as it's a configuration problem rather than a build
problem.